---
title:  <h3>Microsoft Machine Learning Stack for BI & Analytics</h3>
author: <h5>Andreas Effraimis<h5>
output: 
  revealjs::revealjs_presentation:
    theme: night
    center: false
---

# BI tools and ML integration

## Welcome note

<i>‘When you’re fundraising, it’s AI. When you’re hiring, it’s ML. When you’re implementing, it’s logistic regression.’</i>
<small>Joe Davison</small>

## Power BI & R integration


We can integrate Power BI with R either to visualize analytical outcomes or self contain an ML model within our dashboards

There are two ways of doing this :

- Create an R data source 
- Create an R visual and execute an external R script

## Power BI ML models

R scripting essentially gives the Power BI user the ability to integrate ane ML models within business dashboads and answer not only descriptive questions but also prescriptive and predictive.

- Traditional BI [ What happend? ]
- Data Science  [ Why it happend? What will happen? ]

# Azure ML Studio

## Visual Process Machine Learning 

Azure Machine Learning Studio is a visual drag and drop model building enviroment.

- Easily build a prototype ML flow
- Productionalize this ML solution via web services utility
- Integrate R & Python Scripts

# SQL Server Machine Learning Services

## In database Data Science operations

Technical programming languages can be utilized to build analytical models in-database without having to move data across networks.

- R with libraries RevoScaleR & MicrosoftML [available since 2016 distribution]
- Python with revoscalepy and microsoftml [available since 2017 distribution]

## R example 

-Define a connection.
<i>connStr <- "Driver=SQL Server;Server=<your-server-name>;
Database=NYCTaxi_Sample;Trusted_Connection=true"</i>

-Specify the input data in a SQL query
<i>sampleQuery <-"SELECT DISTINCT TOP(100) tip_amount FROM 
[dbo].nyctaxi_sample ORDER BY tip_amount DESC;"</i>

-Define a remote compute context based on the remote server
<i>cc <-RxInSqlServer(connectionString=connStr)</i>

-Execute the function using the remote compute context.
<i>rxSummary(formula = ~ ., data = RxSqlServerData(sqlQuery=sampleQuery, connectionString=connStr), computeContext=cc)</i>

-Generate a scatter plot.
<i>rxLinePlot(fare_amount ~ tip_amount, data = RxSqlServerData(sqlQuery=sampleQuery, connectionString=connStr, computeContext=cc), type="p")</i>